/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * user guide available at https://docs.gradle.org/4.10.2/userguide/java_library_plugin.html
 */

import com.google.protobuf.gradle.*

buildscript {
    //    repositories {
//        maven {
//            url "https://plugins.gradle.org/m2/"
//        }
//    }
    dependencies {
        classpath("net.ltgt.gradle:gradle-apt-plugin:0.13")
        classpath("com.google.protobuf:protobuf-gradle-plugin:0.8.6")
    }
}

plugins {
    // Apply the java-library plugin to add support for Java Library
    `java-library`
    idea
    id("com.google.protobuf") version "0.8.6"
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}



dependencies {
    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api("org.apache.commons:commons-math3:3.6.1")


    compile("org.apache.avro:avro:1.8.2")
    compile("com.google.protobuf:protobuf-java:3.6.1")
    implementation("com.google.protobuf:protobuf-java:3.6.1") //3.2.0
    implementation("com.google.protobuf:protobuf-java-util:3.6.1")

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
//    implementation("com.google.guava:guava:23.0")
//    implementation("io.grpc:grpc-all:1.7.0")

    implementation("com.google.cloud:google-cloud-bigquery:0.22.0-beta")
//    {
//        exclude group: 'com.google.protobuf'
//    }


    // Use JUnit test framework
    testImplementation("junit:junit:4.12")
}

// In this section you declare where to find the dependencies of your project

protobuf {

}