package io.anemos.protobeam.convert;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.google.protobuf.Descriptors;
import io.anemos.protobeam.examples.ProtoBeamBasicSpecial;
import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class SpecialTest extends AbstractProtoBigQueryTest {

    private ProtoTableRowExecutionPlan plan;


    @Before
    public void setup() {
        ProtoBeamBasicSpecial x = ProtoBeamBasicSpecial.newBuilder()
                .build();
        plan = new ProtoTableRowExecutionPlan(x);

        byte[] so = SerializeTest.serializeToByteArray(plan);
        plan = (ProtoTableRowExecutionPlan) SerializeTest.deserializeFromByteArray(so, "");
    }

    @Test
    public void testSchema() {
        ProtoBeamBasicSpecial x = ProtoBeamBasicSpecial.newBuilder().build();
        Descriptors.Descriptor descriptor = x.getDescriptorForType();

        String modelRef = "{fields=[{name=test_name, type=STRING}, {name=test_index, type=INT64}, {name=special_enum, type=STRING}, {mode=REPEATED, name=repeated_enum, type=STRING}]}";
        SchemaProtoToBigQueryModel model = new SchemaProtoToBigQueryModel();
        assertEquals(modelRef, model.getSchema(descriptor).toString());

        String apiRef = "Schema{fields=[Field{name=test_name, value=Type{value=STRING, fields=null}, mode=null, description=null}, Field{name=test_index, value=Type{value=INTEGER, fields=null}, mode=null, description=null}, Field{name=special_enum, value=Type{value=STRING, fields=null}, mode=null, description=null}, Field{name=repeated_enum, value=Type{value=STRING, fields=null}, mode=REPEATED, description=null}]}";
        SchemaProtoToBigQueryApi api = new SchemaProtoToBigQueryApi();
        assertEquals(apiRef, api.getSchema(descriptor).toString());
    }

    @Test
    public void enumValueFieldTest() {
        ProtoBeamBasicSpecial protoIn = ProtoBeamBasicSpecial.newBuilder()
                .setSpecialEnum(ProtoBeamBasicSpecial.EnumSpecial.BAR)
                .build();
        testPingPong(plan, protoIn);
    }

    @Test
    public void enumValueRepeatedTest() {
        ProtoBeamBasicSpecial protoIn = ProtoBeamBasicSpecial.newBuilder()
                .addRepeatedEnum(ProtoBeamBasicSpecial.EnumSpecial.FOO)
                .addRepeatedEnum(ProtoBeamBasicSpecial.EnumSpecial.BAR)
                .build();
        testPingPong(plan, protoIn);
    }

}
